### ISSUE TITLE
Show marker on hover

### ISSUE THREAD

**Issue by ShutovAleksey** [planitjs/planit#6]
Hello! At first I would like to thank you for the great work. But actually I have a question about this plugin. How can I show marker on hover event? I really need it as I use click event to create new markers? It seems that it was a default behavior in the previous version of this plugin.

Thank you!

**Comment by seancdavis** [comment]
Thank you, @ShutovAleksey!

Are you asking to show a marker when you hover on another element? Or are you asking to work with a marker when you hover on that marker?

**Comment by ShutovAleksey** [comment]
Sorry that knocked you up. I need to show tooltip container when mouse is over the marker.

**Comment by seancdavis** [comment]
Ah, yes, you can still do that! I noticed I don't have the event callbacks documented. It's easiest to bind this callback when you initialize `planit`. This particular callback is `markerMouseOver`.

A simple example looks like this:

```js
p = planit.new({
  markers: [
    {
      coords: [12, 45],
      color: '#ccc'
    },
    {
      coords: [5.44, 91],
      draggable: true
    }
  ],
  markerMouseOver: function(event, marker){
    console.log(event);
    console.log(marker);
  }
});
```

The `markerMouseOver

**Comment by seancdavis** [comment]
Ah, yes, you can still do that! I noticed I don't have the event callbacks documented. It's easiest to bind this callback when you initialize `planit`. This particular callback is `markerMouseOver`.

A simple example looks like this:

``` js
p = planit.new({
  markers: [
    {
      coords: [12, 45],
      color: '#ccc'
    },
    {
      coords: [5.44, 91],
      draggable: true
    }
  ],
  markerMouseOver: function(event, marker){
    console.log(event);
    console.log(marker);
  }
});
```

The `markerMouseOver` event fires whenever you mouseover any marker. It returns the event object and the marker object. So, to show the tooltip, you could do something like this:

``` js
p = planit.new({
  markers: [
    {
      coords: [12, 45],
      color: '#ccc'
    },
    {
      coords: [5.44, 91],
      draggable: true,
      infobox: {
        position: 'top',
        html: 'Hello world!',
        arrow: 'bottom'
      }
    }
  ],
  markerMouseOver: function(event, marker){
    marker.showInfobox();
    marker.unhideInfobox();
  },
  markerMouseOut: function(event, marker){
    marker.hideInfobox();
  }
});
```

**Comment by ShutovAleksey** [comment]
Thank you very much, @seancdavis !

**Comment by ShutovAleksey** [comment]
And how can I show infobox for just added marker? If I click the container, plugin adds new marker but doesn't show infobox unless I hover it. I'm trying to call marker.showInfobox(); but marker is undefined until I hover it. 

Thank you @seancdavis !

**Comment by seancdavis** [comment]
Moving this question to a new issue, as it is a separate topic.
