### ISSUE TITLE
Question: Disabling draggable programmatically

### ISSUE THREAD

**Issue by c198130** [planitjs/planit#7]
I'm trying to disable dragging after creating a new draggable marker - let's say I have a button to set position and I don't want the user to be able to reposition the marker further.  Assuming I have the marker instance, is there a way to do that?

I've tried `marker.update({draggable:false});` but it does not stop the marker from being repositioned.  Do I need to access the draggable() of the object in some other manner?

More background on use case
 I'm trying to build an method to allow markers to be repositioned. On a marker click, I'd like to: disable dragging for all other markers except this one - allow the clicked marker to be repositioned - display a form to set position (and write said position to my DB) and then set the draggable for the current marker to false.

Thanks!

**Comment by seancdavis** [comment]
@c198130: Your thinking (`marker.update({draggable:false});`) is exactly how I would do it. I had just left out a few pieces that were keeping this from working.

I've pushed the fix, which is released in `v1.0.2`. It's updated here, on npm, and you should see it soon on jsdelivr.

**Comment by c198130** [comment]
Thanks so much!
