### ISSUE TITLE
Infobox position

### ISSUE THREAD

**Issue by ShutovAleksey** [planitjs/planit#8]
Hello Sean!

It is actually a question, not an issue. Is it possible to align infobox vertically by marker? I mean top for example? Because its vertical align now is middle. But infobox can have big height.

Thank you!

**Comment by seancdavis** [comment]
Hi @ShutovAleksey!

Can you show me an example of what you mean? Maybe a screenshot of the problem and what you're trying to accomplish?

**Comment by ShutovAleksey** [comment]
Yes, sure! 
Here is what I'm working on. 
As you can see this infobox is aligned in the middle of marker. Can I handle it's vertical alignment? 
![screenshot](https://cloud.githubusercontent.com/assets/10271575/13728968/88c1137a-e939-11e5-8ab8-af552bad835e.jpg)

**Comment by seancdavis** [comment]
The infobox can snap to one of eight spots ([see `infobox` options here](http://planit.seancdavis.me/api_reference/plan/add-marker.html)).

Without trying to override Planit, you could see if `top-right` or `bottom-right` would suit your needs in this example.

You may also consider overriding the CSS if you want a little more control—the selector would be `.planit-container .planit-infobox-container .planit-infobox.active`.
