### ISSUE TITLE
How to set the cursor coordinates to (Coords / data-xpc & data ypc

### ISSUE THREAD

**Issue by ddd3nick** [planitjs/planit#9]
This a Question.

_Your code is awesome and i love it. I was to use it in a page to mark few things on a image. I want the user to do this._

I checked the (add_on_click.html) and it has the link which add the marker to the container. I can make it drag-able so that the use can move it to whatever position he wants.

I edited the script to get an cursor position and then to replace it with the coords.

```
<script>

      p = planit.new({

        container: 'planit',
  image: {
    url: 'http://nicksoftwaresolutions.com/img/top-bg.jpg',
    zoom: false,
  }

      });

      $('#planit').click(function(e){

        // e.preventDefault();

        var offset = $(this).offset();

    var rx = e.pageX - offset.left;
    var ry = e.pageY - offset.top;

    // var rx = e.pageX ;
    // var ry = e.pageY ;

    alert ("X:" + rx + ", Y:" + ry);

        p.addMarker({
          coords: [rx, ry],

          // coords: [rx, ry],

          draggable: true,
                infobox: {
                        html: "<h2>Hello World</h2><p>I am a marker!</p>",
                        position: 'top-left',
                        arrow: true
                    },
                id: 'marker-01',
                class: "my-markers",
                 color: "#CEA052",
                size: 40

        });
      });
    </script>
```

I placed an alert to see the output.

**Example:**

![question 1](https://cloud.githubusercontent.com/assets/16975440/15796780/bd6a27d6-2a22-11e6-85ec-16db72bca8b1.PNG)

The Mouse Click happened on **LEFT:** 399  **TOP:** 97. most of the times the marker goes way off from the canvas even 3000/4000px from the container.

But the coords are placing the marker in a different place.

I did check the .js file and was unable to determine where to change this. If you could give me a tip, it would be great.

Simply, if a user click on the image / container, the marker should show up at that point :)

**Comment by seancdavis** [comment]
Unfortunately, there's no super easy way to do this because I don't have a plan click callback available to you.

The reason it's not working is because you're creating the marker with pixels, but [`addMarker` wants percentages of the container](http://planit.seancdavis.me/api_reference/plan/add-marker.html).

But, by redoing some of the logic I have [here](https://github.com/seancdavis/planit/blob/master/source/javascripts/planit/events.coffee#L17-L24), we can make this work.

Here's how I'd write the javascript:

``` js
p = planit.new({
  container: 'planit',
  image: {
    url: 'http://nicksoftwaresolutions.com/img/top-bg.jpg',
    zoom: false,
  }
});

$('#planit').click(function(e){
  var xPx = e.pageX - p.container.offset().left,
      yPx = e.pageY - p.container.offset().top,
      wImg = p.image.width(),
      hImg = p.image.height(),
      xImg = parseInt(p.image.css('left')),
      yImg = parseInt(p.image.css('top')),
      xPc = ((xPx + Math.abs(xImg)) / wImg) * 100,
      yPc = ((yPx + Math.abs(yImg)) / hImg) * 100

  p.addMarker({
    coords: [xPc, yPc],
    draggable: true,
    infobox: {
      html: "<h2>Hello World</h2><p>I am a marker!</p>",
      position: 'top-left',
      arrow: true
    },
    id: 'marker-01',
    class: "my-markers",
     color: "#CEA052",
    size: 40
  });
});
```

And [here's a working fiddle](https://jsfiddle.net/seancdavis/wyrjv7kf/).

**Comment by ddd3nick** [comment]
Thank you soon much for replying :) it helped me a lot :)
